# Generated by Django 5.2.7 on 2025-10-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
    ]
