# Generated by Django 5.2.7 on 2025-10-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_alter_contact_email_alter_contact_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(default='DefaultName', max_length=20),
        ),
    ]
