# Generated by Django 5.2.7 on 2025-10-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_remove_contact_name_alter_contact_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('user', 'User')], default='user', max_length=10),
        ),
    ]
